#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running tests
go test -cover -tags=test ./...

k3s server &
sleep 10

export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
export PATH=$(pwd)/bin:$PATH

rio-controller &
rio install --check

cd ./tests
tox -- -n $(nproc)
cd ..
